apiVersion: batch/v1
kind: Job
metadata:
  name: gke-training-data-commit
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1000
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: data-commit
        image: gcr.io/automatictrainingcicd/data-commit:latest
        env:
          - name: gmail_password
            valueFrom:
              secretKeyRef:
                name: gmail-secrets
                key: gmail_password
          - name: email_address
            value: svirahonda@gmail.com
      restartPolicy: OnFailure